spring:
  application:
    name: spring-boot-demo

  datasource:
    # MySQL数据库配置
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo.entity
